export const activitiesData = [
    {
        id: 1,
        icon: "🏃",
        title: "Corrida em Grupo",
        category: "Atividade Física",
        date: "22 Nov às 07:00",
        location: "Parque Central",
        vacancies: "18 de 30 vagas",
    },
    {
        id: 2,
        icon: "🍻",
        title: "Happy Hour Virtual",
        category: "Interação Social",
        date: "22 Nov às 18:00",
        location: "Online",
        vacancies: "32 de 50 vagas",
    },
    {
        id: 3,
        icon: "🧘",
        title: "Meditação Guiada",
        category: "Bem-Estar",
        date: "23 Nov às 12:00",
        location: "Sala de Meditação",
        vacancies: "15 de 20 vagas",
    },
    {
        id: 4,
        icon: "💬",
        title: "Palestra: Gestão do Estresse",
        category: "Desenvolvimento",
        date: "24 Nov às 14:00",
        location: "Auditório",
        vacancies: "67 de 100 vagas",
    },
    {
        id: 5,
        icon: "🔥",
        title: "Sessão Anti-Burnout",
        category: "Saúde Mental",
        date: "25 Nov às 10:00",
        location: "Sala de Workshops",
        vacancies: "8 de 15 vagas",
    },
];
